# Generated by Django 5.2.3 on 2025-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_horoscopedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_of_birth',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
